name: bohr.io deploy [NPM]
on: push
permissions: write-all
jobs:
  deploy:
    name: Deploy on bohr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            /home/runner/.cache
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install OIDC Client from Core Package
        run: npm --logevel=error install @actions/core
        shell: bash

      - name: Get ID token from Github OIDC provider
        uses: actions/github-script@v6
        id: get_id_token
        with:
          script: |
            const coreAction = require('@actions/core');
            coreAction.setOutput('id_token', await coreAction.getIDToken());
             
      - name: Deploy on bohr.io
        run: npx --yes bohr@latest deploy
        env:
          ID_TOKEN: ${{ steps.get_id_token.outputs.id_token }}
          GITHUB_TOKEN: ${{ github.token }}
          FORCE_COLOR: "2"
        shell: bash
